[package]
name = "merkle_notes"
version = "0.1.0"
authors = ["Dusty Phillips <dusty@beanstalk.network>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
shrinkwraprs = "0.2.1"

[dev-dependencies]
assert_matches = "1.3.0"
color-backtrace = "0.1"
